/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.bdmf.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum ACT_ON_BEHALF_CLIENT_ID_TYPES implements org.apache.avro.generic.GenericEnumSymbol<ACT_ON_BEHALF_CLIENT_ID_TYPES> {
  COKIS, BPKN, ISIS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ACT_ON_BEHALF_CLIENT_ID_TYPES\",\"namespace\":\"com.commerzbank.bdmf.ptr.fields100\",\"symbols\":[\"COKIS\",\"BPKN\",\"ISIS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
