/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.bdmf.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum ORDER_ACTN_TYPES implements org.apache.avro.generic.GenericEnumSymbol<ORDER_ACTN_TYPES> {
  NEWO, CANCL, RJCT, TRIG, REME, REMA, REMH, CHME, CHMO, CAME, CAMO, EXPI, PARF, FILL, INACT, REMO, CACL, RJTCL, CAEXC  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ORDER_ACTN_TYPES\",\"namespace\":\"com.commerzbank.bdmf.ptr.fields100\",\"symbols\":[\"NEWO\",\"CANCL\",\"RJCT\",\"TRIG\",\"REME\",\"REMA\",\"REMH\",\"CHME\",\"CHMO\",\"CAME\",\"CAMO\",\"EXPI\",\"PARF\",\"FILL\",\"INACT\",\"REMO\",\"CACL\",\"RJTCL\",\"CAEXC\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
