/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.bdmf.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum PTT_EXMPT_REASONS implements org.apache.avro.generic.GenericEnumSymbol<PTT_EXMPT_REASONS> {
  PORTF, PCKGTRX, ESCB  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PTT_EXMPT_REASONS\",\"namespace\":\"com.commerzbank.bdmf.ptr.fields100\",\"symbols\":[\"PORTF\",\"PCKGTRX\",\"ESCB\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
