/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.bdmf.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum QUOTE_CXL_REASONS implements org.apache.avro.generic.GenericEnumSymbol<QUOTE_CXL_REASONS> {
  MKTDIST, LMTEXH, OUTFM, OUTTECH, OTHR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"QUOTE_CXL_REASONS\",\"namespace\":\"com.commerzbank.bdmf.ptr.fields100\",\"symbols\":[\"MKTDIST\",\"LMTEXH\",\"OUTFM\",\"OUTTECH\",\"OTHR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
