/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.bdmf.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum SHORT_SELLING_INDS implements org.apache.avro.generic.GenericEnumSymbol<SHORT_SELLING_INDS> {
  SSHO, SSEX, SELL, UNDI  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SHORT_SELLING_INDS\",\"namespace\":\"com.commerzbank.bdmf.ptr.fields100\",\"symbols\":[\"SSHO\",\"SSEX\",\"SELL\",\"UNDI\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
