/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.bdmf.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum STTLM_DELIVERY_TYPES implements org.apache.avro.generic.GenericEnumSymbol<STTLM_DELIVERY_TYPES> {
  PHYS, CASH, OPTL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"STTLM_DELIVERY_TYPES\",\"namespace\":\"com.commerzbank.bdmf.ptr.fields100\",\"symbols\":[\"PHYS\",\"CASH\",\"OPTL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
