/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.bdmf.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum TRADING_CAPACITY_INDS implements org.apache.avro.generic.GenericEnumSymbol<TRADING_CAPACITY_INDS> {
  DEAL, MTCH, AOTC  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TRADING_CAPACITY_INDS\",\"namespace\":\"com.commerzbank.bdmf.ptr.fields100\",\"symbols\":[\"DEAL\",\"MTCH\",\"AOTC\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
