/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ksr.avrodata.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum FIN_INSTR_ID_INT_TYPES implements org.apache.avro.generic.GenericEnumSymbol<FIN_INSTR_ID_INT_TYPES> {
  ISIN, WPKN, CUSIP, IDDS, INTID, SEDOL, RIC, RED, BBG, EXTS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FIN_INSTR_ID_INT_TYPES\",\"namespace\":\"com.commerzbank.bdmf.ptr.fields100\",\"symbols\":[\"ISIN\",\"WPKN\",\"CUSIP\",\"IDDS\",\"INTID\",\"SEDOL\",\"RIC\",\"RED\",\"BBG\",\"EXTS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
