/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ksr.avrodata.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum OPTION_EXERCISE_STYLES implements org.apache.avro.generic.GenericEnumSymbol<OPTION_EXERCISE_STYLES> {
  EURO, AMER, ASIA, BERM, OTHR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OPTION_EXERCISE_STYLES\",\"namespace\":\"com.commerzbank.bdmf.ptr.fields100\",\"symbols\":[\"EURO\",\"AMER\",\"ASIA\",\"BERM\",\"OTHR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
