/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ksr.avrodata.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum ORDER_RESTRICTION_TYPES implements org.apache.avro.generic.GenericEnumSymbol<ORDER_RESTRICTION_TYPES> {
  SESR, VFAR, VFCR, OTHR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ORDER_RESTRICTION_TYPES\",\"namespace\":\"com.commerzbank.bdmf.ptr.fields100\",\"symbols\":[\"SESR\",\"VFAR\",\"VFCR\",\"OTHR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
