/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ksr.avrodata.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum PASSV_AGGR_INDS implements org.apache.avro.generic.GenericEnumSymbol<PASSV_AGGR_INDS> {
  PASS, AGGR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PASSV_AGGR_INDS\",\"namespace\":\"com.commerzbank.bdmf.ptr.fields100\",\"symbols\":[\"PASS\",\"AGGR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
