/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ksr.avrodata.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum SEND_ENTITY_ID_TYPES implements org.apache.avro.generic.GenericEnumSymbol<SEND_ENTITY_ID_TYPES> {
  COKIS, BPKN, ISIS, INTID, DPTNR, LEI  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SEND_ENTITY_ID_TYPES\",\"namespace\":\"com.commerzbank.bdmf.ptr.fields100\",\"symbols\":[\"COKIS\",\"BPKN\",\"ISIS\",\"INTID\",\"DPTNR\",\"LEI\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
