/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ksr.avrodata.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum VALIDITY_PERIOD_INDS implements org.apache.avro.generic.GenericEnumSymbol<VALIDITY_PERIOD_INDS> {
  GDAY, GTCA, GTHT, GTHD, GTDT, GAFT, GAFD, GADT, IOCA, FORK, OTHR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"VALIDITY_PERIOD_INDS\",\"namespace\":\"com.commerzbank.bdmf.ptr.fields100\",\"symbols\":[\"GDAY\",\"GTCA\",\"GTHT\",\"GTHD\",\"GTDT\",\"GAFT\",\"GAFD\",\"GADT\",\"IOCA\",\"FORK\",\"OTHR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
