/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ksr.bdmf.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum BUY_SELL_OMS implements org.apache.avro.generic.GenericEnumSymbol<BUY_SELL_OMS> {
  BUYI, SELL, EXERCISEOPT, RCVPREM, RCVSECAMT, PAYSECAMT, PAYFIXRATE, RCVFIXRATE, PAYSPREAD, RCVSPREAD, RCVCCY, PAYCCY, RCVDIV, PAYDIV, BUYPROT, SELLPROT, RCVCMDTY, DELCMDTY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BUY_SELL_OMS\",\"namespace\":\"com.ksr.bdmf.ptr.fields100\",\"symbols\":[\"BUYI\",\"SELL\",\"EXERCISEOPT\",\"RCVPREM\",\"RCVSECAMT\",\"PAYSECAMT\",\"PAYFIXRATE\",\"RCVFIXRATE\",\"PAYSPREAD\",\"RCVSPREAD\",\"RCVCCY\",\"PAYCCY\",\"RCVDIV\",\"PAYDIV\",\"BUYPROT\",\"SELLPROT\",\"RCVCMDTY\",\"DELCMDTY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
