/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ksr.bdmf.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum COUNTERPARTY_ID_TYPES implements org.apache.avro.generic.GenericEnumSymbol<COUNTERPARTY_ID_TYPES> {
  COKIS, BPKN, ISIS, DPTNR, LEI  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"COUNTERPARTY_ID_TYPES\",\"namespace\":\"com.ksr.bdmf.ptr.fields100\",\"symbols\":[\"COKIS\",\"BPKN\",\"ISIS\",\"DPTNR\",\"LEI\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
