/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ksr.bdmf.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum ORD_ID_EXT_TYPES implements org.apache.avro.generic.GenericEnumSymbol<ORD_ID_EXT_TYPES> {
  TRDVN, BROK, CLNT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ORD_ID_EXT_TYPES\",\"namespace\":\"com.ksr.bdmf.ptr.fields100\",\"symbols\":[\"TRDVN\",\"BROK\",\"CLNT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
