/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ksr.bdmf.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum QTY_NOTATION_TYPES implements org.apache.avro.generic.GenericEnumSymbol<QTY_NOTATION_TYPES> {
  UNIT, NOML, MONE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"QTY_NOTATION_TYPES\",\"namespace\":\"com.ksr.bdmf.ptr.fields100\",\"symbols\":[\"UNIT\",\"NOML\",\"MONE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
