/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ksr.bdmf.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum STRIKE_PRICE_NOTATION_TYPES implements org.apache.avro.generic.GenericEnumSymbol<STRIKE_PRICE_NOTATION_TYPES> {
  MONE, YIEL, PERC  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"STRIKE_PRICE_NOTATION_TYPES\",\"namespace\":\"com.commerzbank.bdmf.ptr.fields100\",\"symbols\":[\"MONE\",\"YIEL\",\"PERC\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
