/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ksr.bdmf.ptr.fields100;
@org.apache.avro.specific.AvroGenerated
public enum WAIVER_IND_TYPES implements org.apache.avro.generic.GenericEnumSymbol<WAIVER_IND_TYPES> {
  LRGS, RFPT, NLIQ, OILQ, PRIC, SIZE, ILQD, ESCB  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"WAIVER_IND_TYPES\",\"namespace\":\"com.ksr.bdmf.ptr.fields100\",\"symbols\":[\"LRGS\",\"RFPT\",\"NLIQ\",\"OILQ\",\"PRIC\",\"SIZE\",\"ILQD\",\"ESCB\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
